### PR TITLE
Polish CI

### PR DESCRIPTION
**Pull request by LingMan**
- The big item here is switching away from actions-rs since the entire organization is unmaintained and the actions are starting to fall apart. 
- The second item is switching the lint job from running with the MSRV to stable, so dialoguer doesn't miss out on newer lints.
- The other two commits are just nits without any functional change.
 
See the individual commits for details.

### CODE REVIEW

**Comment by pksunkara** [comment]
Can you give me an example on where the actions are falling apart? One advantage of cargo action is that it comments the warnings and errors on GitHub.

**Comment by LingMan** [comment]
Quoting from the relevant commit message:

> The actions still use Node 12 and the `set-output` command, both of which are deprecated and will
be removed by Github Actions by Summer 2023. [1][2]
> [...]
> [1] https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> [2] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Review by pksunkara — APPROVED** [review]

**Comment by pksunkara** [comment]
I think this needs rebase.

**Comment by LingMan** [comment]
Rebased. Am I assuming correctly that the other two comments you left about the examples and the tag have resolved themselves? Can't find them in the web UI and you approved the PR, so it look like you deleted them.

**Pull request merged**
